---
- name: restart proxysql
  service:
    name: proxysql
    state: restarted

- name: reload consul
  command: /usr/local/bin/consul reload -http-addr=127.0.0.1:{{ consul_http_port | default(8500) }}
